//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class chargemaster
    {
        public int ChargeId { get; set; }
        public Nullable<decimal> DecorationCharge { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> EventFee { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
