//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerextramaster
    {
        public int CustomerExtraId { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public Nullable<decimal> ExtraCharges { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
