//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class customereventmaster
    {
        public int CustomerEventId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> Gathering { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
