//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class customermaster
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string CustomerEmailId { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
