//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionmaster
    {
        public int id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Question { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IsActive { get; set; }
    }
}
