//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shamsweetsfeedback_androidEntities : DbContext
    {
        public shamsweetsfeedback_androidEntities()
            : base("name=shamsweetsfeedback_androidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminmaster> adminmasters { get; set; }
        public virtual DbSet<advancemaster> advancemasters { get; set; }
        public virtual DbSet<answermaster> answermasters { get; set; }
        public virtual DbSet<categorymaster> categorymasters { get; set; }
        public virtual DbSet<chargemaster> chargemasters { get; set; }
        public virtual DbSet<customercategorymaster> customercategorymasters { get; set; }
        public virtual DbSet<customereventmaster> customereventmasters { get; set; }
        public virtual DbSet<customerextramaster> customerextramasters { get; set; }
        public virtual DbSet<customerextraproductmaster> customerextraproductmasters { get; set; }
        public virtual DbSet<customermaster> customermasters { get; set; }
        public virtual DbSet<customerordermaster> customerordermasters { get; set; }
        public virtual DbSet<customerproductmaster> customerproductmasters { get; set; }
        public virtual DbSet<eventmaster> eventmasters { get; set; }
        public virtual DbSet<extrachargemaster> extrachargemasters { get; set; }
        public virtual DbSet<feedbackmaster> feedbackmasters { get; set; }
        public virtual DbSet<menumaster> menumasters { get; set; }
        public virtual DbSet<menusetupmaster> menusetupmasters { get; set; }
        public virtual DbSet<ordermaster> ordermasters { get; set; }
        public virtual DbSet<productmaster> productmasters { get; set; }
        public virtual DbSet<questionmaster> questionmasters { get; set; }
        public virtual DbSet<remarksmaster> remarksmasters { get; set; }
        public virtual DbSet<storemaster> storemasters { get; set; }
        public virtual DbSet<usermaster> usermasters { get; set; }
        public virtual DbSet<website_login> website_login { get; set; }
        public virtual DbSet<badfeedbacksmsmaster> badfeedbacksmsmasters { get; set; }
    }
}
